# Generated by Django 6.0.4 on 2026-04-09 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="shipping_address",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
