# Generated by Django 6.0.4 on 2026-04-09 19:07

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0003_add_shipping_address_to_order"),
        ("vendors", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Invoice",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("invoice_number", models.CharField(max_length=50, unique=True)),
                ("issued_at", models.DateTimeField(auto_now_add=True)),
                ("total_amount", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="invoices",
                        to="orders.order",
                    ),
                ),
                (
                    "vendor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="invoices",
                        to="vendors.vendorprofile",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["vendor", "issued_at"],
                        name="orders_invo_vendor__8863e8_idx",
                    ),
                    models.Index(
                        fields=["order"], name="orders_invo_order_i_e9463d_idx"
                    ),
                ],
            },
        ),
    ]
